import './style.css';
import {facts} from '../lib/facts.js';
import {groups,wording} from './label-copy.js';
const root=document.querySelector('#app');
root.innerHTML=`<header><a class="brand" href="./"><img class="brand-lock" src="${import.meta.env.BASE_URL}lock.svg" width="29" height="29" alt=""> Privacy Facts</a><a class="github-link" href="https://github.com/thenewpotato/privacy-facts" target="_blank" rel="noopener noreferrer">GitHub ↗</a></header>
<main><section class="intro"><div class="eyebrow"><span></span> KNOW WHAT YOU’RE AGREEING TO</div><h1>The fine print.<br><em>In plain sight.</em></h1><p class="lead">A nutrition label for your privacy.<br>Drop in a policy. See what’s inside.</p>
<form id="analyze-form"><label for="url">Privacy policy URL</label><div class="input-wrap"><span aria-hidden="true">↗</span><input id="url" type="url" placeholder="https://example.com/privacy" autocomplete="url" required><button id="submit" type="submit" aria-label="Analyze policy">→</button></div><div class="try">Try one <button type="button" data-url="https://typesafe.ai/legal/privacy-policy">TypeSafe ↗</button><button type="button" data-url="https://docs.granola.ai/help-center/policies/privacy-policy">Granola ↗</button><button type="button" data-url="https://lovable.dev/privacy">Lovable ↗</button><button type="button" data-url="https://nessielabs.com/privacy">Nessie ↗</button></div><details id="paste"><summary>Or paste the policy text</summary><textarea id="text" placeholder="Paste the full policy here…" aria-label="Policy text" maxlength="60000"></textarea></details><div id="error" role="alert" hidden></div></form>
<div id="progress" aria-live="polite" hidden><span class="spinner"></span><span>Reading the fine print…</span></div>
<div class="intro-foot"><span class="tiny-mark">✳</span><div>Fresh policy. Fresh analysis.<br><span>Powered by Jev.</span></div></div></section>
<section class="result-wrap" aria-label="Privacy Facts label"><div class="paper-top"><span id="label-kind">THE PRIVACY NUTRITION LABEL</span><span>↓ THE GOOD STUFF</span></div><article class="label"><div class="label-heading">Privacy Facts</div><div class="serving"><span>Serving size</span><strong>1 privacy policy</strong></div><div class="serving"><span>Policy for</span><strong id="domain">your next sign-up</strong></div><div class="thick-rule"></div><div class="amount">WHAT’S IN THE FINE PRINT</div><div class="verdict"><span id="verdict-label">Permission<br>to know more.</span><span class="asterisk">✳</span></div><div class="medium-rule"></div><div class="columns"><span>What happens to your data?</span><span>Answer · Jev confidence</span></div><div id="rows"></div><div class="label-foot"><strong>Made for funsies.</strong><p>AI can get things wrong. This isn’t legal advice. Tap a row for the policy text; check the original before making decisions.</p></div></article><div id="result-meta"></div></section></main>
<footer><span>Small label. Big questions.</span><span>Made for the “I agree” generation.</span></footer>`;
const el=id=>document.getElementById(id);let busy=false;
function tone(f,status){if(['not_stated','unclear'].includes(status))return 'unknown';if(f.id==='retention')return ['as_needed','indefinite'].includes(status)?'caution':'neutral';if(status==='opt_in')return 'good';if(status==='conditional')return 'conditional';if(status==='not_applicable')return 'neutral';return (status==='yes')===(f.direction==='protection')?'good':'caution';}
function renderRows(rows){el('rows').replaceChildren();for(const group of groups){const section=document.createElement('section');section.className='fact-group';const heading=document.createElement('h2');heading.textContent=group.title;section.append(heading);el('rows').append(section);for(const [id,label,nested] of group.items){const f=rows.find(item=>item.id===id);if(!f)continue;const row=document.createElement('details');row.className=nested?'fact nested':'fact';const summary=document.createElement('summary');const name=document.createElement('span');name.textContent=label;const value=document.createElement('span');value.className=`value ${f.status?tone(f,f.status):'preview'}`;value.textContent=f.status?wording(f,f.status):'—';if(f.status&&Number.isFinite(f.confidence)){const score=document.createElement('span');score.className='confidence';score.textContent=` · ${Math.round(f.confidence*100)}%`;score.title='Jev model confidence in its classification, not a privacy score';score.setAttribute('aria-label',`Jev model confidence: ${Math.round(f.confidence*100)} percent`);value.append(score);}summary.append(name,value);row.append(summary);if(f.status){const content=document.createElement('div');content.className='evidence';const quote=document.createElement('blockquote');quote.textContent=f.evidence||'No supporting clause was identified in the supplied text.';const note=document.createElement('p');note.textContent=`Model confidence: ${Math.round(f.confidence*100)}% · ${f.evidence?'Suggested supporting clause; review its scope and exceptions.':'Absence of disclosure does not establish actual practice.'}`;content.append(quote,note);row.append(content);}else{row.addEventListener('click',e=>e.preventDefault());}section.append(row);}}}
renderRows(facts);
document.querySelectorAll('[data-url]').forEach(b=>b.addEventListener('click',()=>{el('url').value=b.dataset.url;el('text').value='';el('url').required=true;el('url').focus();}));
el('text').addEventListener('input',()=>{el('url').required=!el('text').value.trim();});
el('analyze-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;el('submit').disabled=true;el('error').hidden=true;el('progress').hidden=false;el('label-kind').textContent='READING A FRESH COPY';root.classList.add('analyzing');
 try{const response=await fetch(`${import.meta.env.BASE_URL}api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(el('text').value.trim()?{text:el('text').value}:{url:el('url').value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not analyze this policy.');renderRows(data.rows);el('domain').textContent=data.domain;el('label-kind').textContent='YOUR PRIVACY LABEL';el('verdict-label').textContent=`${data.rows.length} facts.\nZero fine print.`;el('result-meta').textContent=`${data.model} · ${(data.durationMs/1000).toFixed(2)}s total · Tap any row to read the policy text`;if(innerWidth<850)document.querySelector('.result-wrap').scrollIntoView({behavior:'smooth',block:'start'});
 }catch(err){el('error').textContent=err.message;el('error').hidden=false;el('label-kind').textContent='NEW ANALYSIS NOT COMPLETED';}finally{busy=false;el('submit').disabled=false;el('progress').hidden=true;root.classList.remove('analyzing');}});
